### ISSUE TITLE
Resize embedded YouTube video for mobile

### ISSUE THREAD

**Issue by michael-small** [michael-small/gatsbyTestV2#5]
Extends out beyond the page on mobile. May just be a property of the embedded code?

**Comment by UtkarshKr007** [comment]
On the Responsive_iframe branch in commit 20f4b25, I have included the youtube video three times. The first one is how we had it inside _section2 of the components.md_. That is not detected by the gatsby-remark-responsive-iframe and has no responsive div automatically placed around it. 

The second video is putting the iframe tag in _the body of the components.md_ file as just markdown which is detected by the responsive iframe plugin and has a styled div around it. 

The last video is putting the iframe tag on the ComponenetsPage.js inside two divs and adding CSS rules to those divs. These CSS rules I though was what Content.css was using to keep iframes responsive, but turns out the css regarding iframes in Content.css wasn't applying at all to iframes as commenting them out didn't break the responsive iframes across the website.

Going forward we also have to consider that from the end-user perspective whether it's inside a template or just part of the markdown, the code displays as just an <iframe></iframe> tag. We will need to create a template, so they only need to upload a video and we just insert that into the source of an iframe tag.

Another thing to consider would be this great plugin for embedding videos specifically. 
[Official Docs](https://www.gatsbyjs.org/packages/gatsby-remark-embed-video/)
[More detailed article that troubleshoots the implementation](https://scotch.io/tutorials/embedding-videos-in-your-gatsbyjs-sites)

**Comment by UtkarshKr007** [comment]
I am busy until this wednesday, so I effectively can't continue work on this during this development cycle. If anyone wants to go ahead, otherwise we should adapt one of the two responsive embedded video on the master branch for the presentation.  #11 is related to this. The menu is at the center of page which you need to scroll down to find due to the large screen size created by the video.

**Comment by michael-small** [comment]
As far as I can tell, the iframe in the section2 field is the same iframe code in the body, but the one in the body is actually responsive? I wonder if it's because the fields are converted to strings, and that the iframe is a valid enough string to display but it loses some sort of actual functionality. I think that if we could get the code working as a field itself that it would be more sustainable than the CSS. Perhaps we have to make sure the field is cast explicitly to code.

Edit: Perhaps it is this in `Content.js`

```
const HtmlBlock = ({ value }) => {
  if (value.indexOf('<iframe') !== 0) return value
  return (
    <div
      className={`Content--Iframe`}
      dangerouslySetInnerHTML={{
        __html: value
      }}
    />
  )
}
```

This is what I would think should be doing the iframe formatting. Perhaps the class is styled wrong, or we are not passing in the iframe like it should be passed in. Will look into this when I have more time.

**Comment by michael-small** [comment]
I think I figured it out. It does have iframe styling built in and the `Content--Iframe` is its css class. However, it is the formatting of the field that is an issue.

```
section2: |-
  ## You can use videos, images and text.

  <iframe width="1280" height="720"
  src="https://www.youtube.com/embed/rl-ocew9Dzw" frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope;
  picture-in-picture" allowfullscreen></iframe>
```
Above works as intended with our exact iframe. Though if you look at the current `components.md's section2`, you see: 

```
section2: <iframe width="1280" height="720"
  src="https://www.youtube.com/embed/rl-ocew9Dzw" frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope;
  picture-in-picture" allowfullscreen></iframe>
```
The important thing is not the spacing, it's the **|-**. I've noticed weird things like that which I don't know the function of, but they are evidently important for formatting and recognition of either the data type or css class. 

Edit: In fact, it's about stripping end of string whitespace. That could be all that is wrecking the recognition of it as a validly formatted iframe. See ["Chomp Modifiers"](https://rollout.io/blog/yaml-tutorial-everything-you-need-get-started/) from "YAML Tutorial: Everything You Need to Get Started in Minutes" by Eric Goebelbecker.

**Comment by UtkarshKr007** [comment]
> Edit: In fact, it's about stripping end of string whitespace. That could be all that is wrecking the recognition of it as a validly formatted iframe. See ["Chomp Modifiers"](https://rollout.io/blog/yaml-tutorial-everything-you-need-get-started/) from "YAML Tutorial: Everything You Need to Get Started in Minutes" by Eric Goebelbecker.

Wow, two characters. Two very significant characters. Amazing Find Michael !!

**Comment by michael-small** [comment]
I'm just wondering how they are automatically placed in or not. Those kind of characters came in the template but after some edits were not consistently there, though that may have been not from editing in the CMS but rather blindly cutting all the field content in the straight up markdown. Next time I have a reason to push up a change to the components page I will try to embed a different video and see if it automatically enters that.
