### ISSUE TITLE
Add a calendar of some format

### ISSUE THREAD

**Issue by michael-small** [michael-small/gatsbyTestV2#9]
Many calendars I have seen online that aren't datepickers are just bad on mobile, or meant for mobile but too simple for desktop. Instead, I think we should either find a React library that has one with different layouts for desktop and mobile and general flexibility in between, OR if it's no too much overhead have a query that chooses between desktop and mobile layout if needed. Personally, I only found one calendar that was good on both desktop and mobile, but it cost money. Big money. 

As an example of standalone ones, which looked decent and I found right away. 

http://jquense.github.io/react-big-calendar/examples/index.html
That is a nice detailed one that would convey a good amount of info on **desktop**. However, it doesn't really scale down to mobile.

http://projects.wojtekmaj.pl/react-calendar/
This one is nice and straightforward on **mobile** and it looks like it is very well supported.

These are merely the first two things I found. I looked at other ones and they seemed alright too. Not saying if we go this approach that we should use either of these libraries per say. 

What do we think?

**Comment by UtkarshKr007** [comment]
92e529310482ce6c49ef427f2e5fbd1fc1f509ab adds a Read Only Google Calendar to the homepage on the Calendar branch.

The url for src inside the iframe tag is essentially a get request that can be modified to include single/multiple calendars as well as other options like the default view(weekly,monthly..), the color of the calendar, print option and much more.

I am thinking either the library can have an admin gmail account for just the library admin staff to edit the google calendar or someone on the admin staff can create a calendar, called "Library Schedule" for example, on an existing account and give other admins edit privileges. In this case, we would modify the url so only "Library Schedule" calendars gets shared from the person's account.

I am going to move this issue to Review tag, because I don't feel comfortable closing it without more discussion.

**Comment by michael-small** [comment]
Remind me to check it out during our presentation meeting and I'll run it. Not on my dev OS right now and about to sleep but that sounds legit.
